# Generated by Django 5.2.17 on 2026-08-11 00:21

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, verbose_name="Номер")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст пункта")),
                (
                    "plain_text",
                    models.TextField(
                        blank=True,
                        help_text="Раскрывается кликом. Это и есть то, что коллеги проговаривают маркером",
                        verbose_name="На человеческом языке",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        default=False,
                        help_text="Подсвечивается. Именно эти пункты обычно и не читают",
                        verbose_name="Важный",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт договора",
                "verbose_name_plural": "Пункты договора",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("design", "Проектирование"),
                            ("supervision", "Авторский надзор"),
                            ("procurement", "Комплектация"),
                        ],
                        max_length=16,
                        verbose_name="Вид",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                ("intro", models.TextField(blank=True, verbose_name="Вводная часть")),
                (
                    "outro",
                    models.TextField(blank=True, verbose_name="Заключительная часть"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Действующий"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Шаблон договора",
                "verbose_name_plural": "Шаблоны договоров",
                "ordering": ["kind", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=40, verbose_name="Номер"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.core.utils.public_token,
                        max_length=32,
                        unique=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("reviewed", "Прочитан"),
                            ("signed", "Подписан"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подписан"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contracts.contracttemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ContractAck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Кто подтвердил"),
                ),
                (
                    "template_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Редакция шаблона"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ack",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подтверждение договора",
                "verbose_name_plural": "Подтверждения договоров",
            },
        ),
        migrations.CreateModel(
            name="ClauseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, verbose_name="Вопрос")),
                ("answer", models.TextField(blank=True, verbose_name="Ответ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отвечено"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="contracts.contractclause",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос по договору",
                "verbose_name_plural": "Вопросы по договору",
                "ordering": ["clause__order"],
            },
        ),
        migrations.AddField(
            model_name="contractclause",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clauses",
                to="contracts.contracttemplate",
                verbose_name="Шаблон",
            ),
        ),
    ]
