# Generated by Django 5.2.17 on 2026-08-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("projects", "0002_taskpreset_project_agreed_amount_budgetchange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="То, что заказчик скачивает и подписывает",
                upload_to="contracts/%Y/%m/",
                verbose_name="Файл договора",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отправлен заказчику"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Кто подписал"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_file",
            field=models.FileField(
                blank=True,
                help_text="Загружает заказчик из своего кабинета",
                upload_to="contracts/signed/%Y/%m/",
                verbose_name="Подписанный экземпляр",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Если договор относится к конкретному этапу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="projects.stage",
                verbose_name="Этап",
            ),
        ),
    ]
