# Generated by Django 5.2.17 on 2026-08-11 00:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Номер")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Бюджет",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Закрыт"),
                ),
            ],
            options={
                "verbose_name": "Этап комплектации",
                "verbose_name_plural": "Этапы комплектации",
                "ordering": ["project", "number"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Позиция")),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Артикул"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Поставщик"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "reserve_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Считается по каждому материалу с учётом его особенностей",
                        max_digits=5,
                        verbose_name="Технический запас, %",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Срок поставки, дней"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("picked", "Подобрано"),
                            ("quoted", "Запрошено КП"),
                            ("compared", "Сравнено"),
                            ("ordered", "Заказано"),
                            ("paid", "Оплачено"),
                            ("shipping", "В пути"),
                            ("arrived", "На объекте"),
                            ("accepted", "Принято"),
                        ],
                        default="picked",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_replacement",
                    models.BooleanField(
                        default=False,
                        help_text="Замена до 15 % от проектной ведомости — рыночная норма",
                        verbose_name="Замена проектной позиции",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Заметка")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.procurementstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция комплектации",
                "verbose_name_plural": "Позиции комплектации",
                "ordering": ["stage", "title"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("active", "В работе"),
                            ("paused", "Пауза"),
                            ("done", "Завершён"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True,
                        help_text="Обещаем дату старта и длительность этапов, а не дату въезда: второе зависит от бригады и поставок",
                        null=True,
                        verbose_name="Дата старта",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_at",
                    models.DateField(blank=True, null=True, verbose_name="Завершён"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="crm.property",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="catalog.servicemodule",
                        verbose_name="Состав работ",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.quote",
                        verbose_name="КП",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="procurementstage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procurement_stages",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Номер")),
                ("title", models.CharField(max_length=200, verbose_name="Этап")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Не начат"),
                            ("in_progress", "В работе"),
                            ("review", "На согласовании"),
                            ("done", "Утверждён"),
                        ],
                        default="waiting",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "waiting_on",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("owner", "Дарья"), ("client", "Заказчик")],
                        default="",
                        max_length=8,
                        verbose_name="Кого ждём",
                    ),
                ),
                (
                    "planned_days",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="План, рабочих дней"
                    ),
                ),
                (
                    "started_at",
                    models.DateField(blank=True, null=True, verbose_name="Начат"),
                ),
                (
                    "finished_at",
                    models.DateField(blank=True, null=True, verbose_name="Завершён"),
                ),
                (
                    "client_wait_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Дней ждали заказчика"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Видит только Дарья",
                        verbose_name="Заметка",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап проекта",
                "verbose_name_plural": "Этапы проекта",
                "ordering": ["project", "number"],
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Помещение"
                    ),
                ),
                ("text", models.TextField(verbose_name="Что поменять")),
                (
                    "author_is_client",
                    models.BooleanField(default=True, verbose_name="От заказчика"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("accepted", "В работе"),
                            ("done", "Выполнена"),
                            ("declined", "Отклонена"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="Ответ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reply_due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Считается по регламенту в рабочих часах",
                        null=True,
                        verbose_name="Ответить до",
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Выполнена"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правка",
                "verbose_name_plural": "Правки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Когда"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=150, verbose_name="Кто"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "stage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="projects.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласование",
                "verbose_name_plural": "Согласования",
            },
        ),
        migrations.CreateModel(
            name="StageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="projects/%Y/%m/", verbose_name="Файл"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл этапа",
                "verbose_name_plural": "Файлы этапа",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SupervisionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1"),
                        max_digits=4,
                        verbose_name="План, часов",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Факт, часов",
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(
                        default=False, verbose_name="Созвон вместо выезда"
                    ),
                ),
                ("report", models.TextField(blank=True, verbose_name="Отчёт")),
                (
                    "issues",
                    models.TextField(blank=True, verbose_name="Расхождения с проектом"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выезд по надзору",
                "verbose_name_plural": "Выезды по надзору",
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="uniq_stage_number"
            ),
        ),
    ]
