# Generated by Django 5.2.17 on 2026-08-11 12:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Пусто — подсказка появляется на любом этапе",
                        null=True,
                        verbose_name="Номер этапа",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Что сделать")),
                (
                    "who",
                    models.CharField(
                        choices=[
                            ("owner", "Дарья"),
                            ("client", "Заказчик"),
                            ("both", "Вместе"),
                        ],
                        default="owner",
                        max_length=8,
                        verbose_name="Кто делает",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Готовая задача",
                "verbose_name_plural": "Готовые задачи",
                "ordering": ["stage_number", "order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="agreed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Стоимость проекта на старте. Всё, что сверх неё, оформляется отдельно и с обоснованием",
                max_digits=12,
                verbose_name="Договорились на сумму",
            ),
        ),
        migrations.CreateModel(
            name="BudgetChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Что меняется"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Со знаком: 30000 — подорожало, -30000 — подешевело",
                        max_digits=12,
                        verbose_name="На сколько",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Обоснование обязательно. Без него это не изменение сметы, а просьба",
                        verbose_name="Почему",
                    ),
                ),
                (
                    "consequence",
                    models.TextField(
                        blank=True,
                        help_text="Заказчик имеет право отказаться, зная последствия",
                        verbose_name="Что будет, если не делать",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "На согласовании"),
                            ("accepted", "Согласовано"),
                            ("declined", "Отклонено"),
                        ],
                        default="proposed",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Решение принято"
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Кто решил"
                    ),
                ),
                (
                    "client_comment",
                    models.TextField(blank=True, verbose_name="Комментарий заказчика"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_changes",
                        to="projects.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_changes",
                        to="projects.stage",
                        verbose_name="Этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение сметы",
                "verbose_name_plural": "Изменения сметы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Имя автора"
                    ),
                ),
                (
                    "author_is_owner",
                    models.BooleanField(default=False, verbose_name="От Дарьи"),
                ),
                ("text", models.TextField(blank=True, verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Прочитано другой стороной"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="projects.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="projects.stage",
                        verbose_name="Этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение по проекту",
                "verbose_name_plural": "Переписка по проекту",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="chat/%Y/%m/", verbose_name="Файл"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Имя файла"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="Размер, байт"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл переписки",
                "verbose_name_plural": "Файлы переписки",
            },
        ),
        migrations.CreateModel(
            name="ProjectPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prepay", "Предоплата"),
                            ("stage", "Оплата этапа"),
                            ("extra", "Доплата"),
                            ("final", "Окончательный расчёт"),
                        ],
                        default="stage",
                        max_length=12,
                        verbose_name="За что",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Назначение"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projects.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="projects.stage",
                        verbose_name="Этап",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата по проекту",
                "verbose_name_plural": "Оплаты по проекту",
                "ordering": ["-paid_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StageTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Что сделать")),
                (
                    "who",
                    models.CharField(
                        choices=[
                            ("owner", "Дарья"),
                            ("client", "Заказчик"),
                            ("both", "Вместе"),
                        ],
                        default="owner",
                        max_length=8,
                        verbose_name="Кто делает",
                    ),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Сделано")),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда сделано"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Пояснение")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача этапа",
                "verbose_name_plural": "Задачи этапа",
                "ordering": ["is_done", "order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["project", "created_at"], name="projects_me_project_704325_idx"
            ),
        ),
    ]
