# Generated by Django 5.2.17 on 2026-08-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_taskpreset_project_agreed_amount_budgetchange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Поправлено"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_decision",
            field=models.BooleanField(default=False, verbose_name="Решение"),
        ),
    ]
