# Generated by Django 5.2.17 on 2026-08-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_message_edited_at_message_is_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagefile",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Подпись"),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Помещение")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Помещение",
                "verbose_name_plural": "Помещения",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="stagefile",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="projects.room",
                verbose_name="Помещение",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("project", "title"), name="uniq_room_title"
            ),
        ),
    ]
