# Generated by Django 5.2.17 on 2026-08-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_stagefile_title_room_stagefile_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpreset",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — заготовка появляется во всех проектах",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_presets",
                to="projects.project",
                verbose_name="Только для проекта",
            ),
        ),
    ]
