# Generated by Django 5.2.17 on 2026-08-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, verbose_name="Chat ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Ник в Telegram"
                    ),
                ),
                (
                    "link_code",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Код привязки"
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Привязан"
                    ),
                ),
                (
                    "notify_stages",
                    models.BooleanField(default=True, verbose_name="Смена этапа"),
                ),
                (
                    "notify_tasks",
                    models.BooleanField(
                        default=True, verbose_name="Новые задачи для меня"
                    ),
                ),
                (
                    "notify_messages",
                    models.BooleanField(default=True, verbose_name="Сообщения"),
                ),
                (
                    "notify_money",
                    models.BooleanField(default=True, verbose_name="Деньги и договоры"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram",
                "verbose_name_plural": "Telegram",
            },
        ),
    ]
