# Generated by Django 5.2.17 on 2026-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_telegramaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Согласие на обработку данных"
            ),
        ),
    ]
