# Generated by Django 5.2.17 on 2026-08-11 00:21

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("crm", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=40, verbose_name="Номер"),
                ),
                ("title", models.CharField(max_length=250, verbose_name="За что")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("issued", "Выставлен"),
                            ("paid", "Оплачен"),
                            ("partial", "Оплачен частично"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.core.utils.public_token,
                        max_length=32,
                        unique=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Оплатить до"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Выставлен"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счёт",
                "verbose_name_plural": "Счета",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("getplatinum", "GetPlatinum"), ("manual", "Вручную")],
                        default="getplatinum",
                        max_length=20,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ID у провайдера"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("succeeded", "Прошёл"),
                            ("failed", "Не прошёл"),
                            ("refunded", "Возвращён"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ провайдера"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.invoice",
                        verbose_name="Счёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_payment_id", ""), _negated=True),
                        fields=("provider", "provider_payment_id"),
                        name="uniq_provider_payment",
                    )
                ],
            },
        ),
    ]
