# Generated by Django 5.2.17 on 2026-08-11 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Адрес"),
                ),
                (
                    "lead",
                    models.CharField(blank=True, max_length=400, verbose_name="Анонс"),
                ),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "published_at",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Полезное",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CookieConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Сессия"
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("all", "Все"), ("necessary", "Только необходимые")],
                        max_length=16,
                        verbose_name="Выбор",
                    ),
                ),
                (
                    "analytics",
                    models.BooleanField(default=False, verbose_name="Аналитика"),
                ),
                (
                    "policy_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Редакция политики"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Браузер"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Согласие на куки",
                "verbose_name_plural": "Согласия на куки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("privacy", "Политика конфиденциальности"),
                            ("consent", "Согласие на обработку персональных данных"),
                            ("offer", "Публичная оферта"),
                            ("cookies", "Политика в отношении файлов cookie"),
                            ("terms", "Пользовательское соглашение"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="Вид",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown-подобная разметка: ## заголовок, - список",
                        verbose_name="Текст",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата редакции",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Юридический документ",
                "verbose_name_plural": "Юридические документы",
                "ordering": ["kind"],
            },
        ),
        migrations.CreateModel(
            name="Objection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос и возражение",
                "verbose_name_plural": "Вопросы и возражения",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalDataConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="Имя"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Контакт"
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Редакция документа"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Откуда"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Согласие на обработку ПД",
                "verbose_name_plural": "Согласия на обработку ПД",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        default="Дарья", max_length=120, verbose_name="Имя"
                    ),
                ),
                (
                    "owner_title",
                    models.CharField(
                        default="архитектор, дизайнер интерьера",
                        max_length=200,
                        verbose_name="Кто вы",
                    ),
                ),
                (
                    "owner_photo",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="Фото"
                    ),
                ),
                (
                    "owner_about",
                    models.TextField(blank=True, verbose_name="Текст о себе"),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+7 (913) 032-29-08",
                        max_length=32,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Красноярск", max_length=80, verbose_name="Город"
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="Самозанятый",
                        max_length=200,
                        verbose_name="Юридическое имя",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        default="246315111806", max_length=12, verbose_name="ИНН"
                    ),
                ),
                (
                    "workday_start",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Начало рабочего дня"
                    ),
                ),
                (
                    "workday_end",
                    models.PositiveSmallIntegerField(
                        default=19, verbose_name="Конец рабочего дня"
                    ),
                ),
                (
                    "reply_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Считается в рабочем времени, а не в календарном",
                        verbose_name="Срок ответа, рабочих часов",
                    ),
                ),
                (
                    "regulations",
                    models.TextField(
                        blank=True,
                        help_text="Публикуется дословно на сайте и в договоре",
                        verbose_name="Регламент",
                    ),
                ),
                (
                    "wip_limit",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Сверх этого числа новые проекты встают в очередь. Именно этот предел защищает от выгорания",
                        verbose_name="Проектов одновременно",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="StageNorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Номер этапа"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Этап")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Что происходит"),
                ),
                (
                    "what_client_does",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Что делает заказчик"
                    ),
                ),
                (
                    "working_days",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Рабочих дней"
                    ),
                ),
                (
                    "client_days",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Дней на согласование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап работы",
                "verbose_name_plural": "Этапы работы",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="Город"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="Площадь, м²",
                    ),
                ),
                (
                    "style",
                    models.CharField(blank=True, max_length=120, verbose_name="Стиль"),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Коротко"
                    ),
                ),
                ("task", models.TextField(blank=True, verbose_name="Задача")),
                ("solution", models.TextField(blank=True, verbose_name="Решение")),
                ("result", models.TextField(blank=True, verbose_name="Результат")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Имя заказчика"
                    ),
                ),
                (
                    "client_quote",
                    models.TextField(blank=True, verbose_name="Слова заказчика"),
                ),
                (
                    "client_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="portfolio/clients/",
                        verbose_name="Фото заказчика",
                    ),
                ),
                (
                    "client_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Без галочки имя, фото и слова заказчика на сайт не выводятся",
                        verbose_name="Заказчик разрешил публикацию",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="На главную"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Состав работ по объекту. Показывает разницу между «под ключ» и «только чертежи» лучше любого текста",
                        related_name="portfolio_projects",
                        to="catalog.servicemodule",
                        verbose_name="Что было сделано",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект портфолио",
                "verbose_name_plural": "Портфолио",
                "ordering": ["order", "-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/", verbose_name="Фото"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "is_before",
                    models.BooleanField(default=False, verbose_name="Кадр «до»"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.portfolioproject",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
                "ordering": ["order", "id"],
            },
        ),
    ]
