# Generated by Django 5.2.17 on 2026-08-12 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitesettings_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outlet", models.CharField(max_length=150, verbose_name="Издание")),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Заголовок публикации"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Дата"
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        blank=True,
                        help_text="Фрагмент, который стоит показать",
                        verbose_name="Цитата",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="press/", verbose_name="Логотип издания"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to="press/",
                        verbose_name="Обложка или разворот",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация в прессе",
                "verbose_name_plural": "Пресса",
                "ordering": ["order", "-date"],
            },
        ),
        migrations.AddField(
            model_name="portfoliophoto",
            name="is_cover",
            field=models.BooleanField(
                default=False,
                help_text="Показывается в списке работ и первым на странице",
                verbose_name="Главное фото",
            ),
        ),
        migrations.AddField(
            model_name="portfoliophoto",
            name="is_wide",
            field=models.BooleanField(
                default=False,
                help_text="Занимает в мозаике двойную ширину",
                verbose_name="Широкий кадр",
            ),
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="client_video",
            field=models.FileField(
                blank=True,
                help_text="Файл MP4. Показывается только при согласии заказчика",
                upload_to="portfolio/video/",
                verbose_name="Видеоотзыв",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="dzen",
            field=models.URLField(blank=True, verbose_name="Дзен"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pinterest",
            field=models.URLField(blank=True, verbose_name="Pinterest"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vk",
            field=models.URLField(blank=True, verbose_name="ВКонтакте"),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="client_consent",
            field=models.BooleanField(
                default=False,
                help_text="Без галочки имя, фото, видео и слова заказчика на сайт не выводятся",
                verbose_name="Заказчик разрешил публикацию",
            ),
        ),
    ]
