# Generated by Django 5.2.17 on 2026-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pressmention_portfoliophoto_is_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioproject",
            name="built_on",
            field=models.CharField(
                blank=True,
                help_text="Когда объект сдан: «март 2025»",
                max_length=60,
                verbose_name="Реализация",
            ),
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="designed_on",
            field=models.CharField(
                blank=True,
                help_text="Как в подписи: «январь 2023»",
                max_length=60,
                verbose_name="Проект",
            ),
        ),
    ]
