# Generated by Django 5.2.17 on 2026-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_portfolioproject_built_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="payment_note",
            field=models.TextField(
                blank=True,
                help_text="Показывается на счёте вместо кнопки оплаты картой: номер для перевода по СБП, банк, назначение платежа",
                verbose_name="Как оплатить переводом",
            ),
        ),
    ]
