# Generated by Django 5.2.17 on 2026-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_payment_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressmention",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Чтобы можно было прочитать целиком, не выходя с сайта",
                upload_to="press/pdf/",
                verbose_name="PDF статьи или номера",
            ),
        ),
        migrations.AddField(
            model_name="pressmention",
            name="issue",
            field=models.CharField(
                blank=True,
                help_text="Как на обложке: «№273, август 2026»",
                max_length=80,
                verbose_name="Номер",
            ),
        ),
        migrations.AddField(
            model_name="pressmention",
            name="spread",
            field=models.ImageField(
                blank=True,
                help_text="Скан или снимок страницы: видно, что публикация настоящая",
                upload_to="press/",
                verbose_name="Разворот со статьёй",
            ),
        ),
        migrations.AlterField(
            model_name="pressmention",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="press/", verbose_name="Обложка номера"
            ),
        ),
    ]
