# Generated by Django 5.2.17 on 2026-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_pressmention_file_pressmention_issue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="owner_intro",
            field=models.TextField(
                blank=True,
                help_text="Два-три предложения в блоке «Обо мне» на главной странице",
                verbose_name="Коротко о себе (главная)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="owner_intro_title",
            field=models.CharField(
                blank=True,
                default="Я не робот",
                max_length=120,
                verbose_name="Заголовок блока на главной",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="owner_about",
            field=models.TextField(
                blank=True,
                help_text="Полный рассказ. Заменяет текст на странице целиком",
                verbose_name="Текст о себе (страница «Обо мне»)",
            ),
        ),
    ]
