# Generated by Django 5.2.17 on 2026-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_owner_texts_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioproject",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Галочка поднимает объект в начало витрины на главной. Свободные места добираются последними опубликованными — главная не пустеет, даже если ничего не отмечено",
                verbose_name="На главную первым",
            ),
        ),
    ]
