# Generated by Django 5.2.17 on 2026-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_featured_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="reply_hours",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="Считается в рабочем времени, а не в календарном. Девять часов — это один рабочий день с 10:00 до 19:00, то есть те самые «сутки», которые обещает регламент. При 24 рабочих часах страница пообещает среду на вопрос, заданный вечером пятницы, — и разойдётся с регламентом, напечатанным рядом на той же странице",
                verbose_name="Срок ответа, рабочих часов",
            ),
        ),
    ]
