# Generated by Django 5.2.17 on 2026-08-11 00:21

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "messenger",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Мессенджер"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Сарафан, сайт, соцсети. Основной канал — сарафан, и его надо считать, а не заменять",
                        max_length=120,
                        verbose_name="Откуда пришёл",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Видит только Дарья",
                        verbose_name="Заметки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="crm.client",
                        verbose_name="Кто порекомендовал",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Красноярск", max_length=80, verbose_name="Город"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=250, verbose_name="Адрес"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new", "Новостройка"),
                            ("secondary", "Вторичка"),
                            ("house", "Дом"),
                            ("commercial", "Коммерческое помещение"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Площадь по документам, м²",
                    ),
                ),
                (
                    "measured_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Расхождение с БТИ до 3–4 м² — норма. По ней идёт перерасчёт",
                        max_digits=7,
                        null=True,
                        verbose_name="Площадь по обмеру, м²",
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Помещений"
                    ),
                ),
                (
                    "keys_received",
                    models.BooleanField(default=False, verbose_name="Ключи получены"),
                ),
                (
                    "has_builders",
                    models.BooleanField(default=False, verbose_name="Свои строители"),
                ),
                (
                    "desired_move_in",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Когда хотят заехать"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("qualified", "Квалифицирована"),
                            ("call", "Созвон назначен"),
                            ("quote_sent", "КП отправлено"),
                            ("contract", "Договор"),
                            ("won", "В работе"),
                            ("lost", "Отказ"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Источник"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "answers",
                    models.JSONField(blank=True, default=dict, verbose_name="Анкета"),
                ),
                (
                    "next_action",
                    models.CharField(
                        default="Связаться",
                        max_length=200,
                        verbose_name="Следующий шаг",
                    ),
                ),
                (
                    "next_action_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Когда"
                    ),
                ),
                (
                    "last_touch_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее касание"
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Причина отказа"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="crm.property",
                        verbose_name="Объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["next_action_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.core.utils.public_token,
                        max_length=32,
                        unique=True,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=7,
                        verbose_name="Площадь, м²",
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Помещений"
                    ),
                ),
                (
                    "supervision_months",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Месяцев надзора"
                    ),
                ),
                (
                    "procurement_stages",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Этапов комплектации"
                    ),
                ),
                (
                    "design_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Проектирование",
                    ),
                ),
                (
                    "realization_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Реализация",
                    ),
                ),
                (
                    "extra_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Разовое",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлено"),
                            ("opened", "Открыто"),
                            ("accepted", "Принято"),
                            ("expired", "Просрочено"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий Дарьи"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Впервые открыто"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="crm.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "complexity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.complexityfactor",
                        verbose_name="Характер интерьера",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="crm.lead",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.preset",
                        verbose_name="Пресет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коммерческое предложение",
                "verbose_name_plural": "Коммерческие предложения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("unit", models.CharField(max_length=10, verbose_name="Единица")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Пусто — индивидуальный расчёт",
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.servicemodule",
                        verbose_name="Модуль",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция КП",
                "verbose_name_plural": "Позиции КП",
                "ordering": ["module__block", "module__order"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "next_action_at"], name="crm_lead_status_e44261_idx"
            ),
        ),
    ]
