# Generated by Django 5.2.17 on 2026-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="В архиве с"
            ),
        ),
    ]
