# Generated by Django 5.2.17 on 2026-08-13 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_client_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="partner",
            field=models.OneToOneField(
                blank=True,
                help_text="Муж, жена, соавтор решения — работает в том же кабинете",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_as_partner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Второй аккаунт",
            ),
        ),
    ]
