# Generated by Django 5.2.17 on 2026-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_client_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_spam",
            field=models.BooleanField(default=False, verbose_name="Похоже на спам"),
        ),
        migrations.AddField(
            model_name="lead",
            name="spam_reason",
            field=models.CharField(blank=True, max_length=200, verbose_name="Почему"),
        ),
    ]
