# Generated by Django 5.2.17 on 2026-08-11 00:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplexityFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Пояснение"
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        verbose_name="Коэффициент",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Характер интерьера",
                "verbose_name_plural": "Характер интерьера",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ModuleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "house_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("foundation", "Фундамент"),
                            ("walls", "Стены"),
                            ("windows", "Окна"),
                            ("facade", "Фасад"),
                            ("finish", "Отделка"),
                            ("roof", "Крыша"),
                            ("light", "Свет в окнах"),
                            ("garden", "Сад у крыльца"),
                        ],
                        max_length=16,
                        verbose_name="Элемент дома",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа выбора",
                "verbose_name_plural": "Группы выбора",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=16, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "short_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Коротко (для блока)"
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        choices=[
                            ("design", "Проектирование"),
                            ("realization", "Реализация"),
                            ("extra", "Разовое"),
                        ],
                        default="design",
                        max_length=16,
                        verbose_name="Блок",
                    ),
                ),
                (
                    "house_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("foundation", "Фундамент"),
                            ("walls", "Стены"),
                            ("windows", "Окна"),
                            ("facade", "Фасад"),
                            ("finish", "Отделка"),
                            ("roof", "Крыша"),
                            ("light", "Свет в окнах"),
                            ("garden", "Сад у крыльца"),
                        ],
                        max_length=16,
                        verbose_name="Элемент дома",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("sqm", "за м²"),
                            ("fixed", "фиксированно"),
                            ("stage", "за этап"),
                            ("month", "в месяц"),
                            ("visit", "за выезд"),
                            ("custom", "индивидуальный расчёт"),
                        ],
                        default="sqm",
                        max_length=10,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Для «за м²» — цена одного квадратного метра",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Входит всегда, снять в конструкторе нельзя",
                        verbose_name="Обязательный",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, если услуга ещё не отработана и обещать её рано",
                        verbose_name="Показывать на сайте",
                    ),
                ),
                (
                    "affected_by_complexity",
                    models.BooleanField(
                        default=True,
                        help_text="Умножается на коэффициент характера интерьера",
                        verbose_name="Зависит от сложности",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Что входит"),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Что на выходе"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Рабочих дней"
                    ),
                ),
                (
                    "not_included",
                    models.TextField(blank=True, verbose_name="Что не входит"),
                ),
                (
                    "warning",
                    models.TextField(
                        blank=True,
                        help_text="Показывается, когда модуль снят. Не запугивание, а факт",
                        verbose_name="Что вы берёте на себя",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules",
                        to="catalog.modulegroup",
                        verbose_name="Группа выбора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модуль услуги",
                "verbose_name_plural": "Каталог услуг",
                "ordering": ["block", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("sqm", "за м²"),
                            ("fixed", "фиксированно"),
                            ("stage", "за этап"),
                            ("month", "в месяц"),
                            ("visit", "за выезд"),
                            ("custom", "индивидуальный расчёт"),
                        ],
                        max_length=10,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Комментарий"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.servicemodule",
                        verbose_name="Модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение цены",
                "verbose_name_plural": "История цен",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Одной строкой"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Кому подходит"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Стартовое состояние конструктора. Клиент не собирает с нуля, а разбирает готовый дом",
                        verbose_name="Выбран по умолчанию",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="presets",
                        to="catalog.servicemodule",
                        verbose_name="Состав",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пресет",
                "verbose_name_plural": "Пресеты",
                "ordering": ["order"],
            },
        ),
    ]
