# Generated by Django 5.2.17 on 2026-08-11 05:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complexity_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Выключено — вопрос про характер интерьера не показывается, цена одна для всех. Включается одной галочкой в любой момент, коэффициенты и так заведены",
                        verbose_name="Учитывать сложность интерьера",
                    ),
                ),
                (
                    "small_area_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Фикс для маленьких помещений"
                    ),
                ),
                (
                    "small_area_threshold",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("20"),
                        max_digits=6,
                        verbose_name="Площадь до, м²",
                    ),
                ),
                (
                    "small_area_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80000"),
                        help_text="Любой пакет услуг для помещения такой площади стоит эту сумму. На маленьком метраже расчёт за квадрат даёт цифру, за которую работать нельзя: включения там столько же",
                        max_digits=10,
                        verbose_name="Фиксированная цена",
                    ),
                ),
                (
                    "months_per_100_sqm",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Средний срок по практике: объект в 100 м² строится около года от демонтажа до картины на стене. Из этого числа считается ориентировочный срок авторского надзора",
                        verbose_name="Месяцев стройки на 100 м²",
                    ),
                ),
                (
                    "show_grand_total",
                    models.BooleanField(
                        default=True,
                        help_text="Проектирование и надзор всё равно показываются отдельными строками. Общий итог — чтобы «50 000 в месяц» не выглядело меньше, чем оно есть за весь срок стройки",
                        verbose_name="Показывать общий итог",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Правила расчёта",
                "verbose_name_plural": "Правила расчёта",
            },
        ),
        migrations.AddField(
            model_name="servicemodule",
            name="extra_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Для пакета часов: сколько стоит каждый следующий час",
                max_digits=10,
                verbose_name="Цена сверх пакета",
            ),
        ),
        migrations.AddField(
            model_name="servicemodule",
            name="included_units",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0"),
                help_text="Для пакета часов: сколько часов входит в базовую цену",
                max_digits=6,
                verbose_name="Единиц в пакете",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("sqm", "за м²"),
                    ("fixed", "фиксированно"),
                    ("stage", "за этап"),
                    ("month", "в месяц"),
                    ("visit", "за выезд"),
                    ("hours", "пакет часов"),
                    ("custom", "индивидуальный расчёт"),
                ],
                max_length=10,
                verbose_name="Единица",
            ),
        ),
        migrations.AlterField(
            model_name="servicemodule",
            name="unit",
            field=models.CharField(
                choices=[
                    ("sqm", "за м²"),
                    ("fixed", "фиксированно"),
                    ("stage", "за этап"),
                    ("month", "в месяц"),
                    ("visit", "за выезд"),
                    ("hours", "пакет часов"),
                    ("custom", "индивидуальный расчёт"),
                ],
                default="sqm",
                max_length=10,
                verbose_name="Единица",
            ),
        ),
    ]
