# Generated by Django 5.2.17 on 2026-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_pricingsettings_servicemodule_extra_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulegroup",
            name="house_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("foundation", "Пол"),
                    ("walls", "Стены"),
                    ("windows", "Окно"),
                    ("facade", "Мебель"),
                    ("finish", "Отделка пола"),
                    ("roof", "Потолок"),
                    ("light", "Светильник"),
                    ("garden", "Растение"),
                ],
                max_length=16,
                verbose_name="Часть комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="servicemodule",
            name="house_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("foundation", "Пол"),
                    ("walls", "Стены"),
                    ("windows", "Окно"),
                    ("facade", "Мебель"),
                    ("finish", "Отделка пола"),
                    ("roof", "Потолок"),
                    ("light", "Светильник"),
                    ("garden", "Растение"),
                ],
                max_length=16,
                verbose_name="Часть комнаты",
            ),
        ),
    ]
