# Generated by Django 5.2.17 on 2026-08-13 09:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_modulegroup_house_part_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complexityfactor",
            options={
                "ordering": ["kind", "order"],
                "verbose_name": "Коэффициент сложности",
                "verbose_name_plural": "Коэффициенты сложности",
            },
        ),
        migrations.AddField(
            model_name="complexityfactor",
            name="kind",
            field=models.CharField(
                choices=[
                    ("style", "Характер интерьера"),
                    ("condition", "Сложность объекта"),
                ],
                default="style",
                max_length=16,
                verbose_name="Вид",
            ),
        ),
        migrations.AlterField(
            model_name="complexityfactor",
            name="description",
            field=models.TextField(blank=True, verbose_name="Пояснение"),
        ),
        migrations.AlterField(
            model_name="complexityfactor",
            name="factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Для характера — множитель (1.15). Для сложности — надбавка (0.10)",
                max_digits=4,
                verbose_name="Коэффициент",
            ),
        ),
    ]
