# Generated by Django 5.2.17 on 2026-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_alter_complexityfactor_options_complexityfactor_kind_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingsettings",
            name="complexity_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Выключено — вопросы про характер интерьера и сложность объекта не показываются, цена одна для всех. Включается одной галочкой в любой момент, коэффициенты и так заведены",
                verbose_name="Учитывать сложность",
            ),
        ),
    ]
